### ISSUE TITLE
Update channel_id when moving cross-section location to another channel

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schematisation-editor#240] opened 2024-06-26 11:59 UTC

**Comment by ldebek** [comment] 2024-06-27 14:37
@leendertvanwolfswinkel Isn't it a duplicate of already closed ticket https://github.com/nens/threedi-schematisation-editor/issues/221 ?

**Closed** 2024-07-01 18:53 UTC
Labels: duplicate, question
