### ISSUE TITLE
Cannot import pipes from memory layer because of "wrong data type"

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schematisation-editor#245] opened 2024-07-02 12:08 UTC
How to reproduce:

- Load any schematisation 
- Import these features 
[Leidingen klaar voor import.zip](https://github.com/user-attachments/files/16067830/Leidingen.klaar.voor.import.zip)
  with this configuration [Pipe.json](https://github.com/user-attachments/files/16067822/Pipe.json)

- Attempt to commit the changes

Error: `wrong data type for attribute 19 of feature -41521: 10`

**Comment by ldebek** [comment] 2024-07-08 11:56
I've succesfully imported and commited provided pipe data. Can't reproduce.

**Comment by leendertvanwolfswinkel** [comment] 2024-07-16 13:36
OK I have found out what's going on. It has something to do with memory layers. You can reproduce this if you load the "Leidingen klaar voor import", run a processing algorithm (e.g. offset lines with a distance of 0.1), save to temporary layer, and try to import that.

**Comment by ldebek** [comment] 2024-07-25 15:03
@leendertvanwolfswinkel I've checked what's going on there and it seems that the issue is that expression use for the `cross_section_width` field returns `String` while filed type is `Real`. I would need to dig further to check why features were commited while importing from the GPKG source, but for now issue might be solved by tweeking an expression.

**Comment by Overmeen** [comment] 2024-08-07 12:54
I cannot reproduce, also not with a temporary layer.

**Comment by Overmeen** [comment] 2024-08-08 14:31
Nothing to be fixed in the plug-in

**Closed by Overmeen** 2024-08-08 14:31 UTC
Labels: bug
